### ISSUE TITLE
Option to dupcheck multi files

### ISSUE THREAD

**Issue by orassayag** [jianbingfang/vscode-dup-checker#6] opened 2019-10-16 11:27 UTC
Hi, will there be an option to dupcheck multi files at once?
Thanks.

**Comment by orassayag** [comment] 2019-10-16 14:34
It's pretty simple. Instead of scanning one file, scan all the solution in the vs code.
You can see the logic working, for example, in the "format-files" extension:
https://marketplace.visualstudio.com/items?itemName=jbockle.jbockle-format-files
(Try it and you will understand how it works and what i'm talking about).
It's just scan all the files and format them. You can do the same logic, and in the output window, display each file - the duplicate lines.
Add option to select all the files in the solution in the ctrl+shift+p ("Check Duplicates (Entire solution)").

**Comment by jianbingfang** [comment] 2019-10-16 14:45
I see. One thing to confirm, the checking logic is separated in each individual file, not to check the duplicates across all files right?

**Comment by orassayag** [comment] 2019-10-16 14:48
The checking process will be on each file separately, but in the end of the entire process you will see in the output window, for example:

------------------ Prepare ------------------
📄utils\file1.js
🔍checking duplicates... done (0.002s)
------------------ Results ------------------
⚙️[trimStart] [trimEnd]
✅4 duplicate values found in 98 lines:
}
},
/***************************************************************************************/
};

------------------ Prepare ------------------
📄utils\file2.js
🔍checking duplicates... done (0.002s)
------------------ Results ------------------
⚙️[trimStart] [trimEnd]
✅4 duplicate values found in 98 lines:
}
},
/***************************************************************************************/
};

and so on...

**Comment by jianbingfang** [comment] 2019-10-16 14:52
Got it! I'll spare some time for this feature this weekend.

**Comment by orassayag** [comment] 2019-10-16 14:53
Thanks a lot :)

**Comment by orassayag** [comment] 2019-10-18 13:15
Yeah, sure.

**Comment by jianbingfang** [comment] 2019-10-18 15:10
Without asking "need to remove the duplicates?"

**Comment by orassayag** [comment] 2019-10-18 15:12
Ho, yeah, sure.

**Comment by jianbingfang** [comment] 2019-10-18 15:19
Good, I have just published v0.1.2, which should be visible to you later.
Feel free to give me your feedback.

**Comment by orassayag** [comment] 2019-10-18 15:24
Ok, I'v installed your update, and the result looks nice, but there is still a major bug: It's not recursive.
It only scan first level of the directory.

**Comment by jianbingfang** [comment] 2019-10-18 15:29
Interesting. But it's late night here, I'll take a look tomorrow.

**Comment by orassayag** [comment] 2019-10-18 15:29
Ok, thanks.

**Comment by jianbingfang** [comment] 2019-10-19 01:52
I found it's caused by GlobPattern "*", which is the default value of `checkAllFilesInclude` I set in v0.1.2.
I have change it to "**" in v0.1.3, so it's able to scan all files recursively. You can change it by yourself in vscode **settings** for other scenarios (see more details in [home page](https://marketplace.visualstudio.com/items?itemName=jianbingfang.dupchecker)).

**Comment by orassayag** [comment] 2019-10-19 02:52
Updated the DupCheck:
1. When it asks me to check 100 files and I press "yes", it's stuck, as you can see in the image.
2. When I press yes, It also pop up error message with the text "Cannot read property 'selections' of undefined" as you can see in the image.

Also, a few questions:
1. Can you add option to modify the type of files to scan? I don't want to scan images, for example, or other extensions that is not code files.
2. Can you add options to ignore some folders? I don't want to scan the "node_modules" folder, for example.

Thanks!

![image](https://user-images.githubusercontent.com/5759067/67136786-09507600-f234-11e9-90d5-b8447725e291.png)

**Comment by jianbingfang** [comment] 2019-10-19 03:05
Actually there does 2 config named `checkAllFilesInclude` and `checkAllFilesExclude`, please see the updated [README](https://github.com/jianbingfang/vscode-dup-checker/blob/master/README.md):

```
  "checkAllFilesInclude": "**"   // GlobPattern for files to include in [Check Duplicates (For All Files)] mode, default: "**"
  "checkAllFilesExclude": ""    // GlobPattern for files to exclude in [Check Duplicates (For All Files)] mode, default: ""
  "checkAllFilesNumLimit": 100  // Maximum number of files to include in [Check Duplicates (For All Files)] mode, default: 100

```

**Comment by orassayag** [comment] 2019-10-19 03:15
When I look on the settings of 
https://marketplace.visualstudio.com/items?itemName=jbockle.jbockle-format-files
(It also has exclude and include options):

![image](https://user-images.githubusercontent.com/5759067/67137039-c55f7000-f237-11e9-8582-e991aa348c55.png)

And it's works good.
I tried to copy the same settings, and it's not working :(

**Comment by jianbingfang** [comment] 2019-10-19 13:20
It definitely won't work if you use the same config of format-files.
Format-files wrappers a simpler self-defined file match syntax beyond [GlobPattern](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) , while DupChecker uses GlobPattern directly, so your `Exclude Patterns` in DupChecker should be:
`"**/{node_modules,dist,.vscode,.chrome}/**"`, which is the standard GlobPattern syntax.

I strongly suggest you take some time to learn [GlobPattern](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) first, it's quite easy!

About the error message of "Cannot read property 'selections' of undefined", I need more details, can you find a way to let me reproduce it?

**Comment by orassayag** [comment] 2019-10-19 13:35
OK, a few things:
1. I changed the settings to your recommendations for the Exclude Patterns and now I get some results, so it's a good start.
2. When I did this configuration, also, the error of "Cannot read property 'selections' of undefined" Is gone. I strongly recommend that "**/{node_modules,dist,.vscode,.chrome}/**" will be the default value for this option.
3. When the bottom message tell me to scan 100 files, and I press "Yes", It's start to scan and I see the results. However, when it enter a file it cannot scan, it throw exception and stop the scan, as you can see in the image below:

![image](https://user-images.githubusercontent.com/5759067/67145894-303b9600-f28e-11e9-93eb-b9beb220eca6.png)

It's recommended to ignore files that you cannot open and move to the next file, don't stop the process. Notify in the output window about the problematic file.

**Comment by jianbingfang** [comment] 2019-10-20 02:45
> 1. I changed the settings to your recommendations for the Exclude Patterns and now I get some results, so it's a good start (I need to do restart to vscode in order it to work).

No necessary to restart/reload vscode after changing settings, 100% verified by myself.

> 2. When I did this configuration, also, the error of "Cannot read property 'selections' of undefined" Is gone. I strongly recommend that "/{node_modules,dist,.vscode,.chrome}/" will be the default value for this option.

I can't agree with you. DupChecker is a general tool, it doesn't make sense to have any domain specified default values. It's your own responsibility to make sure the settings is good for your scenario.

> 3. When the bottom message tell me to scan 100 files, and I press "Yes", It's start to scan and I see the results. However, when it enter a file it cannot scan, it throw exception and stop the scan, as you can see in the image below:

That's the real problem, I'll fix it to skip problematic file and output the error message.

**Comment by jianbingfang** [comment] 2019-10-20 03:47
> It's recommended to ignore files that you cannot open and move to the next file, don't stop the process. Notify in the output window about the problematic file.

I have fix the problem in [pre-release v0.1.4](https://github.com/jianbingfang/vscode-dup-checker/releases/tag/v0.1.4).

You can download the .vsix file from [here](https://github.com/jianbingfang/vscode-dup-checker/releases/download/v0.1.4/dupchecker-0.1.4.vsix) and install it locally ([how to install from VSIX](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)).

I'll publish this version after your check.

**Comment by orassayag** [comment] 2019-10-20 06:01
OK, I'v installed the pre-release version and it's working good!
A few notes:
1. 
> I can't agree with you. DupChecker is a general tool, it doesn't make sense to have any domain specified default values. It's your own responsibility to make sure the settings is good for your scenario.

I can't agree. Not everyone knows or need to know about GlobPattern in order to use this tool. I didn't know it until now, and I have 10 years of programming experience :)
In the end, most of the projects has "node_modules" and use npm, I think that the 1% of users that wish to scan the "node_modules" folder can change the default settings. This is what they for - default settings, for the use of 99% of the users.
But in the end, it's your tool and you call the shot :)

2. As you can see in the image below, I placed the "**/*.{js,jsx}" in the include files, and it works fine :)
But I had some mistakes until I got the right pattern, and I think the error message "DupChecker: no file found in workspace :(", I think It will be wise to write something like "Try change the GlobPattern", or maybe in the error message validate the GlobPattern and if it's not valid, write a message about it (for example, "**/*.js, *.jsx" is valid, but it's clearly want I want, 2 type of files).

3. What is the order of the files that the tool scan? I can't seem to find any logical pattern. For exmaple:

------------------ Prepare 133/174 ------------------
📄c:\Or\_OSREnterprisesAG\Web\VisualizationTool\VisualizationTool\manager\src\shared\enums\stream.enum.js
🔍checking duplicates... done (0.001s)
------------------ Results 133/174 ------------------
⚙️[trimStart] [trimEnd]
✅1 duplicate value found in 33 lines:
]));
------------------ Prepare 134/174 ------------------
📄c:\Or\_OSREnterprisesAG\Web\VisualizationTool\VisualizationTool\client\src\components\ErrorView\ErrorView\ErrorView.jsx
🔍checking duplicates... done (0.001s)
------------------ Results 134/174 ------------------

It scan first inside "manager" folder, and then on the "client" folder, and back to the "manager" folder, and then back again to the "client" folder, can you control the order of the scanning? and if not, maybe to sort the results by the path order.

4. A recommendation for this mode only, It's annoying to see:
------------------ Prepare 134/174 ------------------
------------------ Prepare 135/174 ------------------
------------------ Prepare 136/174 ------------------
------------------ Prepare 137/174 ------------------
------------------ Results 134/174 ------------------
------------------ Results 135/174 ------------------
------------------ Results 136/174 ------------------
------------------ Results 137/174 ------------------

Maybe merge all to one line? It's much more clearer, look:
------------------ Results 134/174 ------------------
📄c:\Or\_OSREnterprisesAG\Web\VisualizationTool\VisualizationTool\manager\src\shared\enums\stream.enum.js
🔍checking duplicates... done (0.001s)
⚙️[trimStart] [trimEnd]
✅1 duplicate value found in 33 lines:
]));
------------------ Results 135/174 ------------------
📄c:\Or\_OSREnterprisesAG\Web\VisualizationTool\VisualizationTool\manager\src\shared\enums\stream.enum.js
🔍checking duplicates... done (0.001s)
⚙️[trimStart] [trimEnd]
✅1 duplicate value found in 33 lines:
]));

![image](https://user-images.githubusercontent.com/5759067/67155364-789e9680-f316-11e9-96d8-94646f195f94.png)

**Comment by jianbingfang** [comment] 2019-10-20 07:31
Sorry, I still stick to my opinion. Yes, the "node_modules" folder is quite a special case, even though, vscode's SEARCH doesn't make it a default exclude. By the way I don't think 99% users of vscode are Node.js developer :)

> 2. As you can see in the image below, I placed the '"/.{js,jsx}"/' in the include files, and it works fine :)

But I had some mistakes until I got the right pattern, and I think the error message "DupChecker: no file found in workspace :(", I think It will be wise to write something like "Try change the GlobPattern", or maybe in the error message validate the GlobPattern and if it's not valid, write a message about it (for example, "/*.js, *.jsx" is valid, but it's clearly want I want, 2 type of files).

Yes, I'll try improve the hint message later to give you more useful info.

> 3. What is the order of the files that the tool scan? I can't seem to find any logical pattern. For exmaple:

The order is determined by `vscode.workspace.findFiles` API, I'm not able to control the order, and I don't know its scanning rule neither :(

If you have no other problems I'll close this issue and publish v0.1.4 after the hint message improvement.

**Comment by orassayag** [comment] 2019-10-20 07:34
No, looks good enough :) Great job & thanks!

**Comment by jianbingfang** [comment] 2019-10-20 13:50
v0.1.4 published.

**Closed by jianbingfang** 2019-10-20 13:50 UTC
